-- 1)What is the information about tables?

SELECT 
	u.USERNAME_ AS KULLANICIADI, u.NAMESURNAME AS ADSOYAD,
	c.CITY AS IL , t.TOWN AS ILCE , d.DISTRICT AS SEMT, a.ADDRESSTEXT AS ACIKADRES ,
	o.ID AS SIPARISID, o.DATE_ AS TARIH, o.TOTALPRICE AS TOPLAMTUTAR, p.DATE_ AS ODEMETARIHI,
	p.APPROVECODE AS BANKAONAYKODU, i.DATE_  AS FATURATARIHI, i.CARGOFICHENO AS KARGOFISNO,
	i2.ITEMCODE AS URUNKODU , i2.ITEMNAME AS URUNADI, o2.AMOUNT AS MIKTAR, 
	o2.UNITPRICE AS BIRIMFIYAT, o2.LINETOTAL AS SATIRTOPLAMI
FROM ORDERS o 
	INNER JOIN USERS u ON u.ID =o.USERID 
	INNER JOIN ADDRESS a ON a.ID = o.ADDRESSID 
	INNER JOIN CITIES c ON c.ID = a.CITYID 
	INNER JOIN TOWNS t ON t.ID = a.TOWNID 
	INNER JOIN DISTRICTS d ON d.ID = a.DISTRICTID 
	INNER JOIN PAYMENTS p ON p.ORDERID = o.ID 
	INNER JOIN INVOICES i ON i.ORDERID = o.ID
	INNER JOIN ORDERDETAILS o2 ON o2.ORDERID  =o.ID 
	INNER JOIN ITEMS i2 ON i2.ID = o2.ITEMID 
WHERE o.ID =26121
--u.NAMESURNAME = 'Ceyda GEZGİNCİ' 

-- 2)What is the total order quantity by city?
	
SELECT 
	c.CITY AS SEHIRADI,
	SUM(o2.LINETOTAL) as TOPLAMSIPARIS_TUTARI,
	SUM(o2.AMOUNT) as TOPLAMSIPARIS_ADEDI,
	COUNT(o2.ID) AS TOPLAMSIPARIS_SAYISI 
FROM ORDERS o 
	INNER JOIN USERS u ON u.ID =o.USERID 
	INNER JOIN ADDRESS a ON a.ID = o.ADDRESSID 
	INNER JOIN CITIES c ON c.ID = a.CITYID 
	INNER JOIN TOWNS t ON t.ID = a.TOWNID 
	INNER JOIN DISTRICTS d ON d.ID = a.DISTRICTID 
	INNER JOIN PAYMENTS p ON p.ORDERID = o.ID 
	INNER JOIN INVOICES i ON i.ORDERID = o.ID
	INNER JOIN ORDERDETAILS o2 ON o2.ORDERID  =o.ID 
	INNER JOIN ITEMS i2 ON i2.ID = o2.ITEMID 
GROUP BY c.CITY
ORDER BY  2 DESC  --SUM(o2.LINETOTAL) 

-- 3)What is the order distribution according to product categories?
SELECT 
	i2.CATEGORY1, i2.CATEGORY2,
	SUM(o2.LINETOTAL) as TOPLAMSIPARIS_TUTARI,
	SUM(o2.AMOUNT) as TOPLAMSIPARIS_ADEDI,
	COUNT(o2.ID) AS TOPLAMSIPARIS_SAYISI ,
	SUM(o2.LINETOTAL)/ SUM(o2.AMOUNT) AS ORTALAMABIRIMFIYAT  
FROM ORDERS o 
	INNER JOIN USERS u ON u.ID =o.USERID 
	INNER JOIN ADDRESS a ON a.ID = o.ADDRESSID 
	INNER JOIN CITIES c ON c.ID = a.CITYID 
	INNER JOIN TOWNS t ON t.ID = a.TOWNID 
	INNER JOIN DISTRICTS d ON d.ID = a.DISTRICTID 
	INNER JOIN PAYMENTS p ON p.ORDERID = o.ID 
	INNER JOIN INVOICES i ON i.ORDERID = o.ID
	INNER JOIN ORDERDETAILS o2 ON o2.ORDERID  =o.ID 
	INNER JOIN ITEMS i2 ON i2.ID = o2.ITEMID 
GROUP BY i2.CATEGORY1,i2.CATEGORY2
ORDER BY 1 
	
-- 4) What are date-based order distribuitons?
SELECT 
	CONVERT(DATE,o.DATE_) AS TARIH,
	SUM(o2.LINETOTAL) AS TOPLAMSIPARIS_TUTAR,
	SUM(o2.AMOUNT) AS TOPLAMSIPARIS_MIKTAR,
	COUNT(o2.ID) AS TOPLAMSIPARIS_SAYISI
FROM ORDERS o 
	INNER JOIN USERS u ON u.ID =o.USERID 
	INNER JOIN ADDRESS a ON a.ID = o.ADDRESSID 
	INNER JOIN CITIES c ON c.ID = a.CITYID 
	INNER JOIN TOWNS t ON t.ID = a.TOWNID 
	INNER JOIN DISTRICTS d ON d.ID = a.DISTRICTID 
	INNER JOIN PAYMENTS p ON p.ORDERID = o.ID 
	INNER JOIN INVOICES i ON i.ORDERID = o.ID
	INNER JOIN ORDERDETAILS o2 ON o2.ORDERID  =o.ID 
	INNER JOIN ITEMS i2 ON i2.ID = o2.ITEMID 
GROUP BY CONVERT(DATE,o.DATE_)
ORDER BY CONVERT(DATE,o.DATE_)
	
-- 5)What is the month and year-based order distribution?
SELECT 
	DATEPART(YEAR,o.DATE_) AS YIL, 
	DATEPART(MONTH,o.DATE_)  AS AY,
	CASE 
		WHEN DATEPART(MONTH,o.DATE_) = 1 THEN 'OCAK'
		WHEN DATEPART(MONTH,o.DATE_) = 2 THEN 'ŞUBAT'
		WHEN DATEPART(MONTH,o.DATE_) = 3 THEN 'MART'
		WHEN DATEPART(MONTH,o.DATE_) = 4 THEN 'NİSAN'
		WHEN DATEPART(MONTH,o.DATE_) = 5 THEN 'MAYIS'
		WHEN DATEPART(MONTH,o.DATE_) = 6 THEN 'HAZİRAN'
		WHEN DATEPART(MONTH,o.DATE_) = 7 THEN 'TEMMUZ'
		WHEN DATEPART(MONTH,o.DATE_) = 8 THEN 'AĞUSTOS'
		WHEN DATEPART(MONTH,o.DATE_) = 9 THEN 'EYLÜL'
		WHEN DATEPART(MONTH,o.DATE_) = 10 THEN 'EKİM'
		WHEN DATEPART(MONTH,o.DATE_) = 11 THEN 'KASIM'
		WHEN DATEPART(MONTH,o.DATE_) = 12 THEN 'ARALIK'
	END AS AYADI,
	SUM(o2.LINETOTAL) AS TOPLAMSIPARIS_TUTAR,
	SUM(o2.AMOUNT) AS TOPLAMSIPARIS_MIKTAR,
	COUNT(o2.ID) AS TOPLAMSIPARIS_SAYISI
FROM ORDERS o 
	INNER JOIN USERS u ON u.ID =o.USERID 
	INNER JOIN ADDRESS a ON a.ID = o.ADDRESSID 
	INNER JOIN CITIES c ON c.ID = a.CITYID 
	INNER JOIN TOWNS t ON t.ID = a.TOWNID 
	INNER JOIN DISTRICTS d ON d.ID = a.DISTRICTID 
	INNER JOIN PAYMENTS p ON p.ORDERID = o.ID 
	INNER JOIN INVOICES i ON i.ORDERID = o.ID
	INNER JOIN ORDERDETAILS o2 ON o2.ORDERID  =o.ID 
	INNER JOIN ITEMS i2 ON i2.ID = o2.ITEMID 
GROUP BY DATEPART(YEAR,o.DATE_),DATEPART(MONTH,o.DATE_)
ORDER BY DATEPART(MONTH,o.DATE_),DATEPART(YEAR,o.DATE_)

-- 6)What is the order distribution by payment type?
SELECT 
	DATEPART(MONTH,DATE_) AS AY, 
	DATEPART(YEAR,DATE_) AS YIL,
	CASE 
			WHEN PAYMENTTYPE = 1 THEN 'KREDI KARTI'
			WHEN PAYMENTTYPE = 2 THEN 'BANKA/HAVALE'
	END AS ODEMETIPIADI,
		SUM(PAYMENTTOTAL) AS TOPLAMTUTAR
FROM PAYMENTS p 
GROUP BY DATEPART(YEAR,DATE_),DATEPART(MONTH,DATE_), PAYMENTTYPE
ORDER BY DATEPART(YEAR,DATE_),DATEPART(MONTH,DATE_) 

-- 7)What are the minimum, maximum and average delivery times? 
SELECT 
	MIN(DATEDIFF(HOUR ,o.DATE_ ,i.DATE_)) AS ENKISA_TESLIMAT,
	MAX(DATEDIFF(HOUR ,o.DATE_ ,i.DATE_)) AS ENUZUN_TESLIMAT, 
	AVG(DATEDIFF(HOUR ,o.DATE_ ,i.DATE_)) AS ORTALAMATESLIMATSURESI_SAAT
FROM ORDERS o 
	INNER JOIN USERS u ON u.ID =o.USERID 
	INNER JOIN ADDRESS a ON a.ID = o.ADDRESSID 
	INNER JOIN CITIES c ON c.ID = a.CITYID 
	INNER JOIN TOWNS t ON t.ID = a.TOWNID 
	INNER JOIN DISTRICTS d ON d.ID = a.DISTRICTID 
	INNER JOIN PAYMENTS p ON p.ORDERID = o.ID 
	INNER JOIN INVOICES i ON i.ORDERID = o.ID
	INNER JOIN ORDERDETAILS o2 ON o2.ORDERID  =o.ID 
	INNER JOIN ITEMS i2 ON i2.ID = o2.ITEMID 
	
-- 8)What is the average delivery time based on customers?
SELECT 
	u.ID,u.NAMESURNAME,
	AVG(DATEDIFF(HOUR ,o.DATE_ ,i.DATE_)) AS ORTALAMATESLIMATSURESI_SAAT,
	MIN(DATEDIFF(HOUR ,o.DATE_ ,i.DATE_)) AS ENKISA_TESLIMAT,
	MAX(DATEDIFF(HOUR ,o.DATE_ ,i.DATE_)) AS ENUZUN_TESLIMAT, 
	SUM(o.TOTALPRICE) AS TOPLAMSIPARIS_TUTARI ,
	COUNT(o.ID) AS SIPARISSAYISI 
FROM ORDERS o 
	INNER JOIN USERS u ON u.ID =o.USERID 
	INNER JOIN ADDRESS a ON a.ID = o.ADDRESSID 
	INNER JOIN CITIES c ON c.ID = a.CITYID 
	INNER JOIN TOWNS t ON t.ID = a.TOWNID 
	INNER JOIN DISTRICTS d ON d.ID = a.DISTRICTID 
	INNER JOIN PAYMENTS p ON p.ORDERID = o.ID 
	INNER JOIN INVOICES i ON i.ORDERID = o.ID
	INNER JOIN ORDERDETAILS o2 ON o2.ORDERID  =o.ID 
	INNER JOIN ITEMS i2 ON i2.ID = o2.ITEMID 
GROUP BY u.ID,u.NAMESURNAME
HAVING AVG(DATEDIFF(HOUR ,o.DATE_ ,i.DATE_)) > 20
ORDER BY 6 DESC 

-- 9)What is the average delivery time based on month and year?
SELECT 
	DATEPART(YEAR,o.DATE_)AS YIL, 
	DATEPART(MONTH,o.DATE_)AS AY, 
	AVG(DATEDIFF(HOUR ,o.DATE_ ,i.DATE_)) AS ORTALAMATESLIMATSURESI_SAAT,
	MIN(DATEDIFF(HOUR ,o.DATE_ ,i.DATE_)) AS ENKISA_TESLIMAT,
	MAX(DATEDIFF(HOUR ,o.DATE_ ,i.DATE_)) AS ENUZUN_TESLIMAT, 
	SUM(o.TOTALPRICE) AS TOPLAMSIPARIS_TUTARI ,
	COUNT(o.ID) AS SIPARISSAYISI 
FROM ORDERS o 
	INNER JOIN USERS u ON u.ID =o.USERID 
	INNER JOIN ADDRESS a ON a.ID = o.ADDRESSID 
	INNER JOIN CITIES c ON c.ID = a.CITYID 
	INNER JOIN TOWNS t ON t.ID = a.TOWNID 
	INNER JOIN DISTRICTS d ON d.ID = a.DISTRICTID 
	INNER JOIN PAYMENTS p ON p.ORDERID = o.ID 
	INNER JOIN INVOICES i ON i.ORDERID = o.ID
	INNER JOIN ORDERDETAILS o2 ON o2.ORDERID  =o.ID 
	INNER JOIN ITEMS i2 ON i2.ID = o2.ITEMID 
GROUP BY DATEPART(YEAR,o.DATE_), DATEPART(MONTH,o.DATE_)
ORDER BY 1,2

-- 10)What is the city-based average delivery time?
SELECT 
	c.CITY,
	AVG(DATEDIFF(HOUR ,o.DATE_ ,i.DATE_)) AS ORTALAMATESLIMATSURESI_SAAT,
	MIN(DATEDIFF(HOUR ,o.DATE_ ,i.DATE_)) AS ENKISA_TESLIMAT,
	MAX(DATEDIFF(HOUR ,o.DATE_ ,i.DATE_)) AS ENUZUN_TESLIMAT, 
	SUM(o.TOTALPRICE) AS TOPLAMSIPARIS_TUTARI ,
	COUNT(o.ID) AS SIPARISSAYISI 
FROM ORDERS o 
	INNER JOIN USERS u ON u.ID =o.USERID 
	INNER JOIN ADDRESS a ON a.ID = o.ADDRESSID 
	INNER JOIN CITIES c ON c.ID = a.CITYID 
	INNER JOIN TOWNS t ON t.ID = a.TOWNID 
	INNER JOIN DISTRICTS d ON d.ID = a.DISTRICTID 
	INNER JOIN PAYMENTS p ON p.ORDERID = o.ID 
	INNER JOIN INVOICES i ON i.ORDERID = o.ID
	INNER JOIN ORDERDETAILS o2 ON o2.ORDERID  =o.ID 
	INNER JOIN ITEMS i2 ON i2.ID = o2.ITEMID 
GROUP BY c.CITY
ORDER BY 2 DESC 

-- 11)Product-based Price Analysis.
SELECT 
	i2.ITEMCODE AS URUNKODU,
	i2.ITEMNAME AS URUNADI,
	MIN(O2.UNITPRICE) AS ENDUSUKFIYAT,
	MAX(O2.UNITPRICE) AS ENYUKSEKFIYAT,
	AVG(O2.UNITPRICE) AS ORTALAMAFIYAT,
	SUM(O2.AMOUNT) AS TOPLAMADET
FROM ORDERS o 
	INNER JOIN USERS u ON u.ID =o.USERID 
	INNER JOIN ADDRESS a ON a.ID = o.ADDRESSID 
	INNER JOIN CITIES c ON c.ID = a.CITYID 
	INNER JOIN TOWNS t ON t.ID = a.TOWNID 
	INNER JOIN DISTRICTS d ON d.ID = a.DISTRICTID 
	INNER JOIN PAYMENTS p ON p.ORDERID = o.ID 
	INNER JOIN INVOICES i ON i.ORDERID = o.ID
	INNER JOIN ORDERDETAILS o2 ON o2.ORDERID  =o.ID 
	INNER JOIN ITEMS i2 ON i2.ID = o2.ITEMID 
GROUP BY i2.ıtemcode , i2.ıtemname