CREATE TABLE [dbo].[CITIES] (
    [ID]        SMALLINT     IDENTITY (1, 1) NOT NULL,
    [COUNTRYID] TINYINT      NULL,
    [CITY]      VARCHAR (50) NULL,
    CONSTRAINT [PK_CITIES] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO

