CREATE TABLE [dbo].[DISTRICTS] (
    [ID]       INT          IDENTITY (1, 1) NOT NULL,
    [TOWNID]   INT          NULL,
    [DISTRICT] VARCHAR (50) NULL,
    CONSTRAINT [PK_DISTRICTS] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO

