CREATE TABLE [dbo].[ITEMS] (
    [ID]        INT           IDENTITY (1, 1) NOT NULL,
    [ITEMCODE]  VARCHAR (50)  NULL,
    [ITEMNAME]  VARCHAR (100) NULL,
    [UNITPRICE] FLOAT (53)    NULL,
    [CATEGORY1] VARCHAR (50)  NULL,
    [CATEGORY2] VARCHAR (50)  NULL,
    [CATEGORY3] VARCHAR (50)  NULL,
    [CATEGORY4] VARCHAR (50)  NULL,
    [BRAND]     VARCHAR (50)  NULL,
    CONSTRAINT [PK_ITEMS] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO

